#### Q2. Row Echelon Form:

In [1]:
import numpy as np
np.random.seed(55)
A = np.random.randint(0, 10, size=(5, 5))
print(" Matrix A:")
print(A)

 Matrix A:
[[7 8 5 7 5]
 [1 6 0 3 8]
 [7 1 5 7 8]
 [3 7 0 7 2]
 [1 8 0 8 9]]


In [2]:
rows, cols = A.shape
for i in range(min(rows, cols)):
    pivot_row = i
    while pivot_row < rows and A[pivot_row, i] == 0:
        pivot_row += 1
    if pivot_row == rows: 
        continue
    A[[i, pivot_row]] = A[[pivot_row, i]]
    A[i] = A[i] / A[i, i]
    for j in range(i + 1, rows):
        A[j] = A[j] - A[j, i] * A[i]

print("\nRow Echelon Form of Matrix A:")
print(A)


Row Echelon Form of Matrix A:
[[1 1 0 1 0]
 [0 1 0 0 1]
 [0 0 1 0 2]
 [0 0 0 1 0]
 [0 0 0 0 1]]
